### ISSUE TITLE
There is no reference to version 0.0.4 in the source code

### ISSUE THREAD

**Issue by cwt** [ponrawee/ssg#5]
Version in `setup.py` is still 0.0.3 and if I run `pip install git+https://github.com/ponrawee/ssg.git` I will get version 0.0.3.

So if I check for outdated package (such as using yolk3k `yolk -U`), it will showing 0.0.4 is available to upgrade, but from my understanding the latest code in github should be (at least) the same version as in PyPI, right?

**Comment by cwt** [comment]
I just push a change to my fork (which will also included in PR #4) to match the version 0.0.4 in PyPI.

**Comment by ponrawee** [comment]
Thank you very much. 

I've merged your pull request. As per @bact 's suggestion on the Thai NLP Facebook group, I've made requirements in setup.py relaxed.
